# Generated by Django 3.1.4 on 2020-12-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Party Name')),
                ('slogan', models.CharField(max_length=100, verbose_name='Party Slogan')),
                ('votes', models.IntegerField(default=0, verbose_name='Total Votes')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Party Logo')),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('votes', models.IntegerField(default=0, verbose_name='Number of Votes')),
                ('img', models.ImageField(upload_to='profileImage', verbose_name='Profile Picture')),
                ('description', models.TextField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.party')),
            ],
        ),
    ]
