# Generated by Django 3.1.4 on 2020-12-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Ariticle Cnotent')),
                ('pub_date', models.DateTimeField(verbose_name='Publish Date')),
            ],
        ),
        migrations.CreateModel(
            name='Aurthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Author Name')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comment')),
                ('pub_date', models.DateTimeField(verbose_name='Publish Date')),
                ('commented_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogHandler.article')),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogHandler.aurthor')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='aurthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogHandler.aurthor'),
        ),
    ]
